"""Tests for OneView server profile detail aggregation."""

from __future__ import annotations

import pytest

from proliant.oneview.cli import _profile_alert_messages, _section_banner, _status_style
from proliant.oneview.profiles import describe_profile, describe_profile_by_serial


PROFILE_URI = "/rest/server-profiles/profile1"
SERVER_URI = "/rest/server-hardware/server1"
EG_URI = "/rest/enclosure-groups/eg1"
SHT_URI = "/rest/server-hardware-types/sht1"
TEMPLATE_URI = "/rest/server-profile-templates/template1"
FW_URI = "/rest/firmware-drivers/fw1"
NETWORK_URI = "/rest/ethernet-networks/net1"


class FakeClient:
    def __init__(self, collections: dict[str, list[dict]], objects: dict[str, dict] | None = None):
        self._collections = collections
        self._objects = objects or {}

    async def get_all(self, uri: str) -> list[dict]:
        return self._collections.get(uri, [])

    async def get(self, uri: str) -> dict:
        return self._objects.get(uri, {})


@pytest.mark.asyncio
async def test_describe_profile_resolves_gui_detail_fields():
    result = await describe_profile(
        FakeClient(
            {
                "/rest/server-profiles": [
                    {
                        "uri": PROFILE_URI,
                        "name": "aci-FM-host1",
                        "status": "Critical",
                        "state": "Normal",
                        "description": "",
                        "serverHardwareUri": SERVER_URI,
                        "serverProfileTemplateUri": TEMPLATE_URI,
                        "serverHardwareTypeUri": SHT_URI,
                        "enclosureGroupUri": EG_URI,
                        "affinity": "Bay",
                        "serialNumberType": "Virtual",
                        "serialNumber": "VCGGKYK003",
                        "macType": "Virtual",
                        "wwnType": "Virtual",
                        "iscsiInitiatorNameType": "AutoGenerated",
                        "iscsiInitiatorName": "iqn.test",
                        "firmware": {
                            "firmwareBaselineUri": FW_URI,
                            "manageFirmware": True,
                            "firmwareInstallType": "FirmwareOnlyOfflineMode",
                            "firmwareActivationType": "Immediate",
                            "firmwareInstallAction": "Update",
                            "consistencyState": "Consistent",
                        },
                        "boot": {"manageBoot": False, "order": []},
                        "bios": {"manageBios": False, "consistencyState": "Unknown", "overriddenSettings": []},
                        "connectionSettings": {
                            "connections": [
                                {
                                    "id": 1,
                                    "name": "mgmt1",
                                    "functionType": "Ethernet",
                                    "networkUri": NETWORK_URI,
                                    "portId": "Mezz 3:1-a",
                                    "mac": "22:00:A3:E0:00:08",
                                    "requestedMbps": "2500",
                                    "allocatedMbps": 2500,
                                    "state": "Deployed",
                                    "status": "OK",
                                }
                            ]
                        },
                    }
                ],
                "/rest/server-hardware": [
                    {
                        "uri": SERVER_URI,
                        "name": "Enclosure-01, bay 3",
                        "model": "SY 480 Gen10",
                        "serialNumber": "MXQ1240F2M",
                        "powerState": "On",
                        "status": "OK",
                        "state": "ProfileApplied",
                        "position": 3,
                    }
                ],
                "/rest/enclosure-groups": [{"uri": EG_URI, "name": "EG-01"}],
                "/rest/server-hardware-types": [{"uri": SHT_URI, "name": "SY 480 Gen10 2"}],
                "/rest/server-profile-templates": [{"uri": TEMPLATE_URI, "name": "gen10-template"}],
                "/rest/ethernet-networks": [{"uri": NETWORK_URI, "name": "VLAN-160"}],
                "/rest/network-sets": [],
            },
            {FW_URI: {"name": "HPE Synergy Service Pack", "version": "SY-2023.05.01"}},
        ),
        "aci-FM-host1",
    )

    assert result["template_name"] == "gen10-template"
    assert result["server_hardware_type"] == "SY 480 Gen10 2"
    assert result["fw_baseline"] == "HPE Synergy Service Pack"
    assert result["fw_version"] == "SY-2023.05.01"
    assert result["connections"] == [
        {
            "id": 1,
            "name": "mgmt1",
            "function_type": "Ethernet",
            "network": "VLAN-160",
            "network_uri": NETWORK_URI,
            "port_id": "Mezz 3:1-a",
            "mac": "22:00:A3:E0:00:08",
            "wwnn": "",
            "wwpn": "",
            "requested_mbps": "2500",
            "allocated_mbps": 2500,
            "maximum_mbps": "",
            "state": "Deployed",
            "status": "OK",
        }
    ]


@pytest.mark.asyncio
async def test_describe_profile_handles_null_template_uri():
    """A profile created directly (not from a template) has
    ``serverProfileTemplateUri: null`` in the OneView API response --
    describe_profile must show "no template" rather than crash trying to
    ``.rsplit()`` a ``None``."""
    result = await describe_profile(
        FakeClient(
            {
                "/rest/server-profiles": [
                    {
                        "uri": PROFILE_URI,
                        "name": "bay7-6820-cna",
                        "status": "OK",
                        "state": "Normal",
                        "description": "",
                        "serverHardwareUri": SERVER_URI,
                        "serverProfileTemplateUri": None,
                        "serverHardwareTypeUri": SHT_URI,
                        "enclosureGroupUri": EG_URI,
                        "affinity": "Bay",
                        "firmware": {},
                        "boot": {},
                        "bios": {},
                        "connectionSettings": {"connections": []},
                    }
                ],
                "/rest/server-hardware": [
                    {
                        "uri": SERVER_URI,
                        "name": "Enclosure-01, bay 7",
                        "model": "SY 480 Gen10",
                        "serialNumber": "CN77090XYZ",
                        "powerState": "Off",
                        "status": "OK",
                        "state": "ProfileApplied",
                        "position": 7,
                    }
                ],
                "/rest/enclosure-groups": [{"uri": EG_URI, "name": "EG-01"}],
                "/rest/server-hardware-types": [{"uri": SHT_URI, "name": "SY 480 Gen10 2"}],
                "/rest/server-profile-templates": [],
                "/rest/ethernet-networks": [],
                "/rest/network-sets": [],
            },
            {},
        ),
        "bay7-6820-cna",
    )

    assert result["template_name"] == ""


def _serial_lookup_collections(hw_extra: dict | None = None):
    """Shared fixture data for describe_profile_by_serial tests: one profile
    assigned to server hardware with serial 'MXQ1240F2M'."""
    hw = {
        "uri": SERVER_URI,
        "name": "Enclosure-01, bay 3",
        "model": "SY 480 Gen10",
        "serialNumber": "MXQ1240F2M",
        "powerState": "On",
        "status": "OK",
        "state": "ProfileApplied",
        "position": 3,
        "serverProfileUri": PROFILE_URI,
    }
    if hw_extra:
        hw.update(hw_extra)
    return {
        "/rest/server-profiles": [
            {
                "uri": PROFILE_URI,
                "name": "HyperV-04",
                "status": "OK",
                "state": "Normal",
                "description": "",
                "serverHardwareUri": SERVER_URI,
                "serverProfileTemplateUri": "",
                "serverHardwareTypeUri": "",
                "enclosureGroupUri": "",
                "firmware": {},
                "boot": {"manageBoot": False, "order": []},
                "bios": {"manageBios": False, "consistencyState": "Unknown", "overriddenSettings": []},
                "connectionSettings": {"connections": []},
            }
        ],
        "/rest/server-hardware": [hw],
        "/rest/enclosure-groups": [],
        "/rest/server-hardware-types": [],
        "/rest/server-profile-templates": [],
        "/rest/ethernet-networks": [],
        "/rest/network-sets": [],
    }


@pytest.mark.asyncio
async def test_describe_profile_by_serial_matches_hardware_serial_not_profile_name():
    """Regression test: COM's oneview.name is the hardware's name/bay label
    (e.g. "MXQ713060B, bay 5"), NOT the profile's own name (e.g.
    "HyperV-04") -- describe_profile_by_serial must match via the hardware's
    serialNumber -> serverProfileUri chain, independent of either name."""
    result = await describe_profile_by_serial(
        FakeClient(_serial_lookup_collections()), "MXQ1240F2M"
    )

    assert result["name"] == "HyperV-04"
    assert result["server_serial"] == "MXQ1240F2M"


@pytest.mark.asyncio
async def test_describe_profile_by_serial_is_case_insensitive():
    result = await describe_profile_by_serial(
        FakeClient(_serial_lookup_collections()), "mxq1240f2m"
    )

    assert result["name"] == "HyperV-04"


@pytest.mark.asyncio
async def test_describe_profile_by_serial_raises_when_hardware_not_found():
    with pytest.raises(ValueError, match="No OneView server hardware found"):
        await describe_profile_by_serial(
            FakeClient(_serial_lookup_collections()), "NOTFOUND123"
        )


@pytest.mark.asyncio
async def test_describe_profile_by_serial_raises_when_hardware_has_no_profile():
    collections = _serial_lookup_collections()
    del collections["/rest/server-hardware"][0]["serverProfileUri"]

    with pytest.raises(ValueError, match="no assigned server profile"):
        await describe_profile_by_serial(FakeClient(collections), "MXQ1240F2M")


@pytest.mark.asyncio
async def test_describe_profile_by_serial_raises_when_profile_uri_not_found():
    collections = _serial_lookup_collections()
    collections["/rest/server-hardware"][0]["serverProfileUri"] = "/rest/server-profiles/missing"

    with pytest.raises(ValueError, match="not found"):
        await describe_profile_by_serial(FakeClient(collections), "MXQ1240F2M")


def test_profile_alert_display_uses_issue_details_and_plain_ok():
    assert _status_style("OK") == "OK"
    assert _status_style("Critical") == "[red]Critical[/red]"

    messages = _profile_alert_messages({
        "status": "Critical",
        "server_status": "OK",
        "connections": [
            {
                "id": 2,
                "name": "map-connection-2",
                "status": "Disabled",
                "state": "Reserved",
                "port_id": "Mezz 3:2-a",
                "allocated_mbps": 0,
            }
        ],
    })

    assert messages == ["Connection map-connection-2 is Disabled (state: Reserved, port: Mezz 3:2-a, allocated: 0 Mbps)."]


def test_section_banner_styles_title_only():
    banner = _section_banner("Connections")

    assert banner.plain == "########### Connections ###########"
    assert [(span.start, span.end, span.style) for span in banner.spans] == [(12, 23, "bold cyan")]