"""Tests for OneView server profile detail aggregation."""

from __future__ import annotations

import pytest

from proliant.oneview.cli import _profile_alert_messages, _section_banner, _status_style
from proliant.oneview.profiles import describe_profile


PROFILE_URI = "/rest/server-profiles/profile1"
SERVER_URI = "/rest/server-hardware/server1"
EG_URI = "/rest/enclosure-groups/eg1"
SHT_URI = "/rest/server-hardware-types/sht1"
TEMPLATE_URI = "/rest/server-profile-templates/template1"
FW_URI = "/rest/firmware-drivers/fw1"
NETWORK_URI = "/rest/ethernet-networks/net1"


class FakeClient:
    def __init__(self, collections: dict[str, list[dict]], objects: dict[str, dict] | None = None):
        self._collections = collections
        self._objects = objects or {}

    async def get_all(self, uri: str) -> list[dict]:
        return self._collections.get(uri, [])

    async def get(self, uri: str) -> dict:
        return self._objects.get(uri, {})


@pytest.mark.asyncio
async def test_describe_profile_resolves_gui_detail_fields():
    result = await describe_profile(
        FakeClient(
            {
                "/rest/server-profiles": [
                    {
                        "uri": PROFILE_URI,
                        "name": "aci-FM-host1",
                        "status": "Critical",
                        "state": "Normal",
                        "description": "",
                        "serverHardwareUri": SERVER_URI,
                        "serverProfileTemplateUri": TEMPLATE_URI,
                        "serverHardwareTypeUri": SHT_URI,
                        "enclosureGroupUri": EG_URI,
                        "affinity": "Bay",
                        "serialNumberType": "Virtual",
                        "serialNumber": "VCGGKYK003",
                        "macType": "Virtual",
                        "wwnType": "Virtual",
                        "iscsiInitiatorNameType": "AutoGenerated",
                        "iscsiInitiatorName": "iqn.test",
                        "firmware": {
                            "firmwareBaselineUri": FW_URI,
                            "manageFirmware": True,
                            "firmwareInstallType": "FirmwareOnlyOfflineMode",
                            "firmwareActivationType": "Immediate",
                            "firmwareInstallAction": "Update",
                            "consistencyState": "Consistent",
                        },
                        "boot": {"manageBoot": False, "order": []},
                        "bios": {"manageBios": False, "consistencyState": "Unknown", "overriddenSettings": []},
                        "connectionSettings": {
                            "connections": [
                                {
                                    "id": 1,
                                    "name": "mgmt1",
                                    "functionType": "Ethernet",
                                    "networkUri": NETWORK_URI,
                                    "portId": "Mezz 3:1-a",
                                    "mac": "22:00:A3:E0:00:08",
                                    "requestedMbps": "2500",
                                    "allocatedMbps": 2500,
                                    "state": "Deployed",
                                    "status": "OK",
                                }
                            ]
                        },
                    }
                ],
                "/rest/server-hardware": [
                    {
                        "uri": SERVER_URI,
                        "name": "Enclosure-01, bay 3",
                        "model": "SY 480 Gen10",
                        "serialNumber": "MXQ1240F2M",
                        "powerState": "On",
                        "status": "OK",
                        "state": "ProfileApplied",
                        "position": 3,
                    }
                ],
                "/rest/enclosure-groups": [{"uri": EG_URI, "name": "EG-01"}],
                "/rest/server-hardware-types": [{"uri": SHT_URI, "name": "SY 480 Gen10 2"}],
                "/rest/server-profile-templates": [{"uri": TEMPLATE_URI, "name": "gen10-template"}],
                "/rest/ethernet-networks": [{"uri": NETWORK_URI, "name": "VLAN-160"}],
                "/rest/network-sets": [],
            },
            {FW_URI: {"name": "HPE Synergy Service Pack", "version": "SY-2023.05.01"}},
        ),
        "aci-FM-host1",
    )

    assert result["template_name"] == "gen10-template"
    assert result["server_hardware_type"] == "SY 480 Gen10 2"
    assert result["fw_baseline"] == "HPE Synergy Service Pack"
    assert result["fw_version"] == "SY-2023.05.01"
    assert result["connections"] == [
        {
            "id": 1,
            "name": "mgmt1",
            "function_type": "Ethernet",
            "network": "VLAN-160",
            "network_uri": NETWORK_URI,
            "port_id": "Mezz 3:1-a",
            "mac": "22:00:A3:E0:00:08",
            "wwnn": "",
            "wwpn": "",
            "requested_mbps": "2500",
            "allocated_mbps": 2500,
            "maximum_mbps": "",
            "state": "Deployed",
            "status": "OK",
        }
    ]


def test_profile_alert_display_uses_issue_details_and_plain_ok():
    assert _status_style("OK") == "OK"
    assert _status_style("Critical") == "[red]Critical[/red]"

    messages = _profile_alert_messages({
        "status": "Critical",
        "server_status": "OK",
        "connections": [
            {
                "id": 2,
                "name": "map-connection-2",
                "status": "Disabled",
                "state": "Reserved",
                "port_id": "Mezz 3:2-a",
                "allocated_mbps": 0,
            }
        ],
    })

    assert messages == ["Connection map-connection-2 is Disabled (state: Reserved, port: Mezz 3:2-a, allocated: 0 Mbps)."]


def test_section_banner_styles_title_only():
    banner = _section_banner("Connections")

    assert banner.plain == "########### Connections ###########"
    assert [(span.start, span.end, span.style) for span in banner.spans] == [(12, 23, "bold cyan")]